import { HiOutlineHome, HiOutlineFolderDownload, HiOutlineStar, HiOutlineCog } from "react-icons/hi";
import { HiMiniHashtag } from "react-icons/hi2";

export const navList = [
    { title: "Dashboard", icon: <HiOutlineHome className='text-xl' /> },
    { title: "Important", icon: <HiOutlineStar className='text-xl' /> },
    { title: "Archive", icon: <HiOutlineFolderDownload className='text-xl' /> },
    { title: "Tags", icon: <HiMiniHashtag className='text-xl' /> }
];

export const names = [
    "PixelPioneer",
    "CloudChaser",
    "CodeMancer",
    "ByteBurst",
    "TechSculptor",
    "LogicLoom",
    "DataDynamo",
    "WebWeaver",
    "BitBlazer",
    "CyberSurge",
    "DigitalDrifter",
    "ByteBard",
    "QuantumQuill",
    "NebulaNomad",
    "VectorVoyager",
    "CipherCrafter",
    "SynthSorcerer",
    "BitBard",
    "CryptoCraft",
    "InfiniteInk",
    "PixelProphet",
    "BinaryBard",
    "CircuitComposer",
    "NeuralNomad",
    "LogicLinguist",
    "TechTrailblazer",
    "QuantumQuest",
    "CodeConductor",
    "ByteBibliophile",
    "WebWizard",
    "DataDancer",
    "LogicLabyrinth",
    "BitBotanist",
    "CyberChronicle",
    "DigitalDynamo",
    "VectorVirtuoso",
    "CipherCaretaker",
    "SynthSculptor",
    "BitBaker",
    "CryptoCrafter",
    "InfiniteIllusion",
    "DigitalDreamer",
    "QuantumQuasar",
    "WebWanderer",
    "PixelPioneer",
    "CloudChaser",
    "CodeMancer",
    "ByteBurst",
    "TechSculptor",
    "LogicLoom",
    "DataDynamo",
    "WebWeaver",
    "BitBlazer",
    "CyberSurge",
    "DigitalDrifter",
    "ByteBard",
    "QuantumQuill",
    "NebulaNomad",
    "VectorVoyager",
    "CipherCrafter",
    "SynthSorcerer",
    "BitBard",
    "CryptoCraft",
    "InfiniteInk",
    "PixelProphet",
    "BinaryBard",
    "CircuitComposer",
    "NeuralNomad",
    "LogicLinguist",
    "TechTrailblazer",
    "QuantumQuest",
    "CodeConductor",
    "ByteBibliophile",
    "WebWizard",
    "DataDancer",
    "LogicLabyrinth",
    "BitBotanist",
    "CyberChronicle",
    "DigitalDynamo",
    "VectorVirtuoso",
    "CipherCaretaker",
    "SynthSculptor",
    "BitBaker",
    "CryptoCrafter",
    "InfiniteIllusion",
    "DigitalDreamer",
    "QuantumQuasar",
    "WebWanderer",
    "PixelPioneer",
    "CloudChaser",
    "CodeMancer",
    "ByteBurst",
    "TechSculptor",
    "LogicLoom",
    "DataDynamo",
    "WebWeaver",
    "BitBlazer",
    "CyberSurge",
    "DigitalDrifter",
    "ByteBard",
    "QuantumQuill",
    "NebulaNomad",
    "VectorVoyager",
    "CipherCrafter",
    "SynthSorcerer",
    "BitBard",
    "CryptoCraft",
    "InfiniteInk",
    "PixelProphet",
    "BinaryBard",
    "CircuitComposer",
    "NeuralNomad",
    "LogicLinguist",
    "TechTrailblazer",
    "QuantumQuest",
    "CodeConductor",
    "ByteBibliophile",
    "WebWizard",
    "DataDancer",
    "LogicLabyrinth",
    "BitBotanist",
    "CyberChronicle",
    "DigitalDynamo",
    "VectorVirtuoso",
    "CipherCaretaker",
    "SynthSculptor",
    "BitBaker",
    "CryptoCrafter",
    "InfiniteIllusion",
    "DigitalDreamer",
    "QuantumQuasar",
    "WebWanderer",
];

export const initialData =
    [
        {
            "id": "heading-1",
            "type": "heading",
            "content": "New Note",
        },
        {
            "id": "paragraph-1",
            "type": "paragraph",
            "content": "Type here..",
        }

    ];
// Feel free to use or modify this array as needed.
